### ISSUE TITLE
Find absolute feedback solution for rotation

### ISSUE THREAD

**Issue by markrusciano** [ISU-MAVRIC/MAVRIC_WheelPod#1]
Maybe some kind of continuous absolute encoder like this hooked up to a belt/gear system with the limited clearance beneath/within the gearbox.
http://www.digikey.com/product-detail/en/EAW0J-C24-AE0128L/EAW0J-C24-AE0128L-ND/3780126

Random Links
- http://www.usdigital.com/products/encoders/absolute/rotary/shaft/ma3
- https://www.youtube.com/watch?v=6r2ZThBgSOc

**Comment by markrusciano** [comment]
@ethanharstad what do you think of maybe having a small belt with a 1:1 ratio between the shaft of the gearbox and a potentiometer/encoder? Seems like it could be simple and space efficient provided we'd be able to protect the belt from dust in some way

**Comment by ethanharstad** [comment]
The problem with belts/gears is that to have a 1:1 ratio we need to have the encoder wheel the same size as the the part of the output shaft that it attaches to. Anything else, by geometry would not have a 1:1 ratio. It is possible we could go for a 2:1 ratio with that digital encoder, that would give us absolute positioning over a 180 degree range but we could dead reckon outside of that range, we would just have to have the wheel pointing +/- 90 degrees from 'forward' when we turn it on. Similarly we could probably get away with up to maybe 6:1 ratio and have to be aligned +/- 30 degrees.

**Comment by markrusciano** [comment]
what about a 360 degree continuous encoder? we could do the 6:1 there and just handle the loop around from 359 to 0

**Comment by markrusciano** [comment]
@JDD314 some ideas for feedback

**Comment by markrusciano** [comment]
Perhaps this: http://www.usdigital.com/products/encoders/absolute/rotary/kit/MAE3
gotta go to class, will add more later

**Comment by markrusciano** [comment]
Going with this one for now: http://www.usdigital.com/products/encoders/absolute/rotary/shaft/ma3

**Comment by markrusciano** [comment]
Also something interesting:
http://www.digikey.com/en/product-highlight/b/bourns/rotary-position-sensors
