### ISSUE TITLE
Determine mounting hole spacing/size

### ISSUE THREAD

**Issue by markrusciano** [ISU-MAVRIC/MAVRIC_WheelPod#10]
@JDD314 we'll need to coordinate on how we want to attach this

**Comment by tkminer** [comment]
mark why do i only get these from you

**Comment by markrusciano** [comment]
I've just been making a lot of issues. I believe you can unsubscribe from this repository or unwatch it if they are bothering you.

**Comment by tkminer** [comment]
oh i will i will you'll see you'll all see

**Comment by markrusciano** [comment]
Going to heat shrink the board and attach it with zip ties
